### ISSUE TITLE
CrawlConfiguration.HttpRequestTimeoutInSeconds value unit

### ISSUE THREAD

**Issue by guidomocha** [sjdirect/abot-dotnet-core#6]
the doc for `CrawlConfiguration.HttpRequestTimeoutInSeconds` says:
/// < summary>
/// Gets or sets the time-out value in **milliseconds**...
/// ...

So, what is the value unit? seconds or milliseconds?

**Comment by Kemyke** [comment]
That's seconds. 
Thanks for the finding.
