### ISSUE TITLE
Access to build server

### ISSUE THREAD

**Issue by sjdirect** [sjdirect/abot-dotnet-core#9]
@Kemyke can you give me access to the build you setup for this project please?

**Comment by Kemyke** [comment]
What is the easiest way to invite you as a collaborator in the appveyor. I only see invitation by email. Is that ok? Can you give me an address to send the invitation to?

**Comment by sjdirect** [comment]
yes please, sjdirect@gmail.com

**Comment by sjdirect** [comment]
Looks like i have access. Thanks!
